version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pdv-postgres
    environment:
      POSTGRES_DB: pdv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pdv-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pdv.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
